apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub-deployment
  labels:
    app: hub-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hub-service
  template:
    metadata:
      labels:
        app: hub-service
    spec:
      containers:
      - name: hub-service
        # Jika menggunakan Azure (ACR), ubah image di bawah ini menjadi:
        # image: namakampusacr.azurecr.io/logistics-hub:latest
        image: logistics-hub:latest
        # Gunakan imagePullPolicy: Never atau IfNotPresent jika test di minikube lokal
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: PORT
          value: "8084"
        - name: TRACKING_SVC_URL
          value: "http://tracking-service:8080"
        - name: ORDER_SVC_URL
          value: "http://order-service:8080"
        - name: AUTH_SVC_URL
          value: "http://auth-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: hub-service
spec:
  selector:
    app: hub-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
