apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification-container
        image: muhiban/notification-service:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: LoadBalancer
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8080
      # nodePort: 30086 # Gunakan angka 86 agar konsisten dengan port 8086