version: '3.8'

services:
  order-service:
    build:
      context: ../../
      dockerfile: deployments/docker/order.Dockerfile
    image: logistics-order:latest
    container_name: logistics-order
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - TRACKING_SVC_URL=http://tracking-service:8083
      - ORDER_SVC_URL=http://order-service:8081
      - AUTH_SVC_URL=http://auth-service:8080
      - PRICING_SVC_URL=http://pricing-service:8082
    networks:
      - logistics-net

  pricing-service:
    build:
      context: ../../
      dockerfile: deployments/docker/pricing.Dockerfile
    image: logistics-pricing:latest
    container_name: logistics-pricing
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - TRACKING_SVC_URL=http://tracking-service:8083
      - ORDER_SVC_URL=http://order-service:8081
      - AUTH_SVC_URL=http://auth-service:8080
      - PRICING_SVC_URL=http://pricing-service:8082
    networks:
      - logistics-net

  tracking-service:
    build:
      context: ../../
      dockerfile: deployments/docker/tracking.Dockerfile
    image: logistics-tracking:latest
    container_name: logistics-tracking
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - TRACKING_SVC_URL=http://tracking-service:8083
      - ORDER_SVC_URL=http://order-service:8081
      - AUTH_SVC_URL=http://auth-service:8080
    networks:
      - logistics-net

  hub:
    build:
      context: ../../
      dockerfile: deployments/docker/hub.Dockerfile
    image: logistics-hub:latest
    container_name: logistics-hub
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
      - TRACKING_SVC_URL=http://tracking-service:8083
      - ORDER_SVC_URL=http://order-service:8081
      - AUTH_SVC_URL=http://auth-service:8080
    networks:
      - logistics-net

  courier:
    build:
      context: ../../
      dockerfile: deployments/docker/courier.Dockerfile
    image: logistics-courier:latest
    container_name: logistics-courier
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - TRACKING_SVC_URL=http://tracking-service:8083
      - ORDER_SVC_URL=http://order-service:8081
      - AUTH_SVC_URL=http://auth-service:8080
    networks:
      - logistics-net

  notification-service:
    build:
      context: ../../
      dockerfile: deployments/docker/notification.Dockerfile
    ports:
      - "8086:8080"
    image: muhiban/notification-service:v1
    container_name: logistics-notification
    environment:
      - PORT=8086
      - TRACKING_SVC_URL=http://tracking-service:8083
      - ORDER_SVC_URL=http://order-service:8081
      - AUTH_SVC_URL=http://auth-service:8080
    networks:
      - logistics-net
  
  auth-service:
    build:
      context: ../../
      dockerfile: deployments/docker/auth.Dockerfile
    ports:
      - "8087:8080"
    image: muhiban/auth-service:v1
    container_name: logistics-auth
    environment:
      - PORT=8087
      - TRACKING_SVC_URL=http://tracking-service:8083
      - ORDER_SVC_URL=http://order-service:8081
      - AUTH_SVC_URL=http://auth-service:8080
    networks:
      - logistics-net

networks:
  logistics-net:
    driver: bridge
